### PR TITLE
Dash interaction

### PR DESCRIPTION
**Pull request by AbolareRoheemah**
Added a loader to dashboard (instead of the connect wallet that is being displayed) when the connect button hasnt yet loaded.
get all cars using fetchOwn Cars hook
Filter for cars bought and cars listed on dashboard

### CODE REVIEW

**Review by yusufroqib — CHANGES_REQUESTED** [review]
Please run build locally and make sure all tests passes

**Comment by yusufroqib** [comment]
You have two `stores` directory. In the project structure from `main` branch, the store is outside the `src` folder
Screenshot 2024-10-17 234103

You didn't fix the hardcoded address in the `useGetOwnCars` hook.
Screenshot 2024-10-17 233341

Some imports are not pointing to the right directory causing build error. Especially the `stores` duplicated folder
Screenshot 2024-10-17 233709

**Review by michojekunle — APPROVED** [review]
Looks Good 🎯🚀

Welldone @AbolareRoheemah 🚀

**Comment by yusufroqib** [comment]
👏🎉

**Pull request merged**
