### PR TITLE
Ft/mechanics

### PR DESCRIPTION
**Pull request by RahmanC**
- [x] featured listings pagination
- [x] top rated mechanics section

### CODE REVIEW

**Review by michojekunle — APPROVED** [review]
Looks good awesome stuff bro 🚀, please check out the conflicts with the main branch

**Comment by yusufroqib** [comment]
Nice job. Pls compare and fix the conflicts with the main branch.

**Review by yusufroqib — CHANGES_REQUESTED** [review]
Kindly fix the conflicts in the two files

**Review by AbolareRoheemah — APPROVED** [review]

**Comment by ro61zzy** [comment]
this is niiiice

**Pull request merged**
