### PR TITLE
Implemented Car details, listing and unlisting 

### PR DESCRIPTION
**Pull request by michojekunle**
- [x] Implemented Car Details Page for dashboard
- [x] Implemented Listing with fixed Price
- [x] Implemented Listing with Auction (except that there might be a bug with the auction contract created a detailed issue here at https://github.com/michojekunle/Vintage-Car-Marketplace/issues/79 )
- [x] Implemeted unlisting functionality

### CODE REVIEW

**Comment by yusufroqib** [comment]
For better structure, kindly bring out the `contracts` folder in the `app`  folder  to the `src` folder. To separate routes from other helpers/constants. Roheemah has done that already. To avoid conflict.

...
 |__src
 |        |__app
          |__contracts

**Review by yusufroqib — CHANGES_REQUESTED** [review]
Added a comment on the review

**Comment by michojekunle** [comment]
> For better structure, kindly bring out the `contracts` folder in the `app` folder to the `src` folder. To separate routes from other helpers/constants. Roheemah has done that already. To avoid conflict.
> 
> ```
>  |__src
>  |    |__app
>  |    |__contracts
>  |
> ```

Alright sure, On it

**Comment by michojekunle** [comment]
@yusufroqib @RahmanC good to merge?

**Comment by yusufroqib** [comment]
LGTM 🚀

**Comment by ceasermikes002** [comment]
👍🏾

**Review by ceasermikes002 — COMMENTED** [review]
Looks good 👍🏾

**Pull request merged**
